"""The narrate() facade: generate, validate, retry once, or refuse.

This is the only entry point the console and CLI use. A narrative that
still fails validation after the retry is not shown to anyone — the
error carries the validator's findings instead. After validation, the
engine's ranking of alternative hypotheses is appended as a
machine-written section: the LLM never discusses hypotheses it was not
given. The LLM gets a voice, never authority.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from whydunit.explain.narrative import DEFAULT_MAX_TOKENS, DEFAULT_MODEL, generate_narrative
from whydunit.explain.validator import ValidationResult, validate_narrative
from whydunit.models import CaseFile


class NarrativeValidationError(RuntimeError):
    """Raised when the narrative still fails validation after retrying."""

    def __init__(self, problems: tuple[str, ...], attempts: int) -> None:
        self.problems = problems
        self.attempts = attempts
        listing = "; ".join(problems)
        super().__init__(f"Narrative failed validation after {attempts} attempt(s): {listing}")


@dataclass(frozen=True, slots=True)
class NarrativeReport:
    """A validated narrative, with its validation record and attempt count.

    ``text`` is the LLM's validated prose plus, when the case ranked
    more than one hypothesis, a deterministic 'Alternatives' section
    appended by code after validation.
    """

    text: str
    validation: ValidationResult
    attempts: int


def _alternatives_note(case: CaseFile) -> str:
    """Machine-written ranking of the non-leading hypotheses. Not LLM output."""
    others = case.hypotheses[1:]
    if not others:
        return ""
    lines = [
        "## Alternatives the engine considered",
        "",
        "*Ranked by the deterministic engine; this section is machine-written,*",
        "*not generated by the LLM.*",
        "",
    ]
    lines += [
        f"- {hypothesis.category.value} — {hypothesis.confidence.value} "
        f"(score {hypothesis.score:.2f})"
        for hypothesis in others
    ]
    return "\n".join(lines)


def _feedback(problems: tuple[str, ...], previous: str) -> str:
    listing = "\n".join(f"- {problem}" for problem in problems)
    return (
        "Your previous attempt failed validation:\n"
        f"{listing}\n\n"
        "Previous attempt:\n"
        f"{previous}\n\n"
        "Rewrite the full narrative from scratch, fixing every problem. "
        "All original rules still apply."
    )


def narrate(
    case: CaseFile,
    client: Any | None = None,
    model: str = DEFAULT_MODEL,
    max_tokens: int = DEFAULT_MAX_TOKENS,
    max_attempts: int = 2,
) -> NarrativeReport:
    """Generate a narrative and enforce validation, retrying once by default."""
    correction: str | None = None
    result: ValidationResult | None = None
    for attempt in range(1, max_attempts + 1):
        text = generate_narrative(
            case,
            client=client,
            model=model,
            max_tokens=max_tokens,
            correction=correction,
        )
        result = validate_narrative(text, case)
        if result.valid:
            note = _alternatives_note(case)
            if note:
                text = f"{text}\n\n{note}"
            return NarrativeReport(text=text, validation=result, attempts=attempt)
        correction = _feedback(result.problems, text)

    assert result is not None  # max_attempts >= 1
    raise NarrativeValidationError(result.problems, max_attempts)
